//! Slug generation, ported from scripts/onboarding_etl.py's slugify().
//! Kept behaviourally identical so category/product slugs generated by
//! the python ETL and the Rust upload-confirm path never disagree.

pub fn slugify(text: &str) -> String {
    let lowered = text.to_lowercase();
    let trimmed = lowered.trim();

    let punctuation_stripped: String = trimmed
        .chars()
        .map(|c| {
            if "()[]{}/\\,;:.+*&#".contains(c) {
                ' '
            } else {
                c
            }
        })
        .collect();

    let hyphenated = punctuation_stripped
        .split_whitespace()
        .collect::<Vec<_>>()
        .join("-");

    let alnum_only: String = hyphenated
        .chars()
        .filter(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || *c == '-')
        .collect();

    let final_slug = alnum_only.trim_matches('-');
    let truncated: String = final_slug.chars().take(60).collect();
    let truncated = truncated.trim_end_matches('-');

    if truncated.is_empty() {
        "item".to_string()
    } else {
        truncated.to_string()
    }
}
